version: '3'
services:
    flask-app:
      build: .
      container_name: flask-app
      ports:
        - "5000:5000"
      networks:
        - monitoring
      restart: unless-stopped # Ensure the container restarts if it fails

    prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      networks:
        - monitoring
      depends_on:
        - flask-app # Ensure Prometheus starts after Flask is available
      restart: unless-stopped

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      networks:
        - monitoring
      depends_on:
        - prometheus # Ensure Grafana starts after Prometheus
      restart: unless-stopped
      volumes:
        - grafana-data:/var/lib/grafana # Persistent data

networks:
  monitoring: # Defines a shared network for all services

volumes:
  grafana-data: # Persistent volume for Grafana dashboards